"""empty message

Revision ID: 98735203e6c2
Revises: 5a4be4a12763
Create Date: 2020-04-14 16:36:31.767492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98735203e6c2'
down_revision = '5a4be4a12763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('joblistings', sa.Column('category', sa.String(), nullable=True))
    op.add_column('joblistings', sa.Column('timeSincePost', sa.String(), nullable=True))
    op.drop_column('joblistings', 'datePosted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('joblistings', sa.Column('datePosted', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('joblistings', 'timeSincePost')
    op.drop_column('joblistings', 'category')
    # ### end Alembic commands ###
